name: Ghink
url: "http://evelynegroen.github.io/"
description: "Uncertainty and sensitivity analysis in environmental impact models"
disqus_shortname: "evelynegroen"
use_leaflet: 1
ga_domain: "ghink.cc"
ga_id: "UA-45360427-2"
blog_more_posts: 5
prettify_theme: "ghink"
markdown: redcarpet
pygments: true
paginate: 3
paginate_path: "blog/page/:num"
timezone: Europe/Lisbon
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
gems:
    - jekyll-sitemap
