name: "Evelyne Groen's page"
url: "http://evelynegroen.github.io/"
description: "Uncertainty and sensitivity analysis in environmental impact models"
disqus_shortname: "evelynegroen"
use_leaflet: 1
blog_more_posts: 5
prettify_theme: "ghink"
markdown: kramdown
pygments: true
highlighter: rouge 
paginate: 5
paginate_path: "blog/page/:num"
timezone: Europe/Amsterdam
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
gems:
    - jekyll-sitemap
